openapi: 3.0.0
info:
    title: Express API Boilerplatesss
    version: 1.0.0
    description: A simple Express API with TypeScript
servers:
    - url: /
paths:
    /health:
        get:
            tags:
                - Health
            summary: Health check
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
components:
    schemas:
    Error:
        type: object
        properties:
            error:
                type: string
            message:
                type: string
