import { z } from 'zod';
import { IEvent } from '../../../types/event.js';

export const EV_BLUEJAY_LOGS_BY_NUMBER: IEvent = {
    id: 'EV_BLUEJAY_LOGS_BY_NUMBER',
    moreInfo: {
        title: 'Number of Logs Containing a Number',
        description: 'Total number of logs whose message contains the configured number.',
        example:
            'If 8 log messages contain the configured number in the selected window, the metric value would be 8.',
    },
    fetcherIds: ['FT_REST_BLUEJAY_LOGS'],
    processConfigSchema: z.object({}),
    process() {
        const events: Record<string, unknown>[] = [];

        return events;
    },
};

export const EV_BLUEJAY_LOGS_BY_LEVEL: IEvent = {
    id: 'EV_BLUEJAY_LOGS_BY_LEVEL',
    moreInfo: {
        title: 'Number of Logs by Level',
        description: 'Total number of logs generated by a specific microservice level.',
        example:
            'If the microservice generated 50 INFO logs in the last month, the metric value would be 50.',
    },
    fetcherIds: ['FT_REST_BLUEJAY_LOGS'],
    processConfigSchema: z.object({}),
    process() {
        const events: Record<string, unknown>[] = [];

        return events;
    },
};
