import { z } from 'zod';
import { IMetric } from '../../../types/metric.js';
import { getFetchResultsWithPipeline } from '../../../db/archive.js';
import { getPeriodStartDateFromAnchorAndPeriod } from '../utils/window.util.js';

export const MT_xx_BLUEJAY_xx_COUNT_LOGS_BY_NUMBER: IMetric = {
    name: 'MT_xx_BLUEJAY_xx_COUNT_LOGS_BY_NUMBER',
    moreInfo: {
        title: 'Number of Logs Containing a Number',
        description: 'Total number of logs whose message contains the configured number.',
        example:
            'If 8 log messages contain the configured number in the selected window, the metric value would be 8.',
    },
    fetcher: 'FT_xx_BLUEJAY_xx_REPORTER_LOGS',
    metricConfigSchema: z.object({
        number: z.number(),
    }),
    auditConfigSchema: z.object({}),
    async process(_date, _window, _metricConfig, _auditConfig) {
        const { number } = _metricConfig as { number: number };
        const date = new Date(_date);
        const anchorDate = new Date(_window.anchorDate);
        const escapeRegex = (value: string): string => {
            return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        };
        const configuredNumberRegex = `(^|\\D)${escapeRegex(String(number))}(\\D|$)`;

        const windowStartDate = getPeriodStartDateFromAnchorAndPeriod(
            date,
            anchorDate,
            _window.period,
        );
        const windowStartTimestampMicros = windowStartDate.getTime() * 1000;
        const dateTimestampMicros = date.getTime() * 1000;

        const pipeline: Record<string, unknown>[] = [
            {
                $match: {
                    fetcherName: 'FT_xx_BLUEJAY_xx_REPORTER_LOGS',
                    status: 'COMPLETED',
                    fetchDate: { $gte: windowStartDate, $lte: date },
                    'data.items': { $exists: true, $type: 'array' },
                },
            },
            { $sort: { fetchDate: -1 } },
            { $limit: 1 },
            { $unwind: '$data.items' },
            { $replaceRoot: { newRoot: '$data.items' } },
            {
                $match: {
                    timestamp: { $gte: windowStartTimestampMicros, $lte: dateTimestampMicros },
                    body: { $regex: configuredNumberRegex },
                },
            },
            {
                $group: {
                    _id: null,
                    evidences: { $push: '$$ROOT' },
                    value: { $sum: 1 },
                },
            },
        ];

        const [aggregatedResult] = await getFetchResultsWithPipeline(pipeline);
        const evidences =
            (aggregatedResult?.evidences as Record<string, unknown>[] | undefined) ?? [];
        const value =
            typeof aggregatedResult?.value === 'number' ? (aggregatedResult.value as number) : 0;

        return { value, evidences };
    },
};

export const MT_xx_BLUEJAY_xx_COUNT_LOGS_BY_LEVEL: IMetric = {
    name: 'MT_xx_BLUEJAY_xx_COUNT_LOGS_BY_LEVEL',
    moreInfo: {
        title: 'Number of Logs by Level',
        description: 'Total number of logs generated by a specific microservice level.',
        example:
            'If the microservice generated 50 INFO logs in the last month, the metric value would be 50.',
    },
    fetcher: 'FT_xx_BLUEJAY_xx_REPORTER_LOGS',
    metricConfigSchema: z.object({
        level: z.string(),
    }),
    auditConfigSchema: z.object({}),
    async process(_date, _window, _metricConfig, _auditConfig) {
        const { level } = _metricConfig as { level: string };
        const date = new Date(_date);
        const anchorDate = new Date(_window.anchorDate);
        const escapeRegex = (value: string): string => {
            return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        };
        const levelRegex = `^${escapeRegex(level)}$`;
        const messageContainsNumberRegex = '\\d+';

        const windowStartDate = getPeriodStartDateFromAnchorAndPeriod(
            date,
            anchorDate,
            _window.period,
        );
        const windowStartTimestampMicros = windowStartDate.getTime() * 1000;
        const dateTimestampMicros = date.getTime() * 1000;

        const pipeline: Record<string, unknown>[] = [
            {
                $match: {
                    fetcherName: 'FT_xx_BLUEJAY_xx_REPORTER_LOGS',
                    status: 'COMPLETED',
                    fetchDate: { $gte: windowStartDate, $lte: date },
                    'data.items': { $exists: true, $type: 'array' },
                },
            },
            { $sort: { fetchDate: -1 } },
            { $limit: 1 },
            { $unwind: '$data.items' },
            { $replaceRoot: { newRoot: '$data.items' } },
            {
                $match: {
                    timestamp: { $gte: windowStartTimestampMicros, $lte: dateTimestampMicros },
                    severityText: { $regex: levelRegex, $options: 'i' },
                    body: { $regex: messageContainsNumberRegex },
                },
            },
            {
                $group: {
                    _id: null,
                    evidences: { $push: '$$ROOT' },
                    value: { $sum: 1 },
                },
            },
        ];

        const [aggregatedResult] = await getFetchResultsWithPipeline(pipeline);
        const evidences =
            (aggregatedResult?.evidences as Record<string, unknown>[] | undefined) ?? [];
        const value =
            typeof aggregatedResult?.value === 'number' ? (aggregatedResult.value as number) : 0;

        return { value, evidences };
    },
};
